# local-compose.yml - Run services on local host
#
# Parse Server will be:     http://localhost:1337/parse
# Parse Dashboard will be:  http://localhost:8080

# Nginx as a load-balancing tier and reverse proxy, with caching and optional SSL termination
nginx:
    extends:
      file: common-services.yml
      service: nginx
    ports:
        - 8080:80
    environment:
        - CONSUL=consul
    links:
        - consul

# Parse server
parse:
    extends:
      file: common-services.yml
      service: parse
    environment:
        - CONSUL=consul
        - PARSE_SERVER_URL=http://localhost:8080/parse
    links:
        - mongodb
        - consul

# Parse dashboard
parse-dashboard:
    extends:
      file: common-services.yml
      service: parse-dashboard
    environment:
        - CONSUL=consul
        - PARSE_DASHBOARD_SERVER_URL=http://localhost:8080/parse
    links:
        - parse
        - consul

# Redis
redis:
    extends:
      file: common-services.yml
      service: redis
    environment:
        - CONSUL=consul
    links:
        - consul

# MongoDB
mongodb:
    extends:
      file: common-services.yml
      service: mongodb
    environment:
        - CONSUL=consul
    links:
        - consul

# Prometheus
prometheus:
    extends:
      file: common-services.yml
      service: prometheus
    environment:
        - CONSUL=consul
    links:
        - consul

# Consul
consul:
    extends:
      file: common-services.yml
      service: consul
